In [41]:
import numpy as np
import pandas as pd
import os
import glob 

src = '../hpcc/topology/'

In [29]:
idname = '2014SBa'

rownum = 1
treenum = 36
nutnum = 1

bname = idname + '_R{}_T{}'.format(rownum, treenum)
fname = bname + '_{:03d}'.format(nutnum)
print(fname)

esrc = src + bname + '/' + fname + '_'
DD = 150
TT = [4,8,16,32,64]

ects = [None for i in range(len(TT))]
for i in range(len(ects)):
    ects[i] = np.loadtxt(esrc + 'd{:04d}_t{:02d}.csv'.format(DD,TT[i]), delimiter=',', dtype=int)

for i in range(len(ects)):
    print(i, TT[i], len(ects[i]), sep='\t')

2014SBa_R1_T36_001
0	4	600
1	8	1200
2	16	2400
3	32	4800
4	64	9600


In [30]:
for i in range(len(ects)):
    print(i, ects[i][:15], sep='\n')

0
[ 2  0  3  2  3  2  2  2  0  1  3  2 -6  2  4]
1
[ 4  2  0  0 -1  3 -9  2  2  3  1  2  2  2  2]
2
[ 13   4   1   2  -2   0  -2   0   1  -1 -10   3   3  -9  -9]
3
[-15  13  16   4  -3   1  -2   2   4  -2   2   0   2  -2   2]
4
[ -6 -15   8  13 -10  16  -4   4   0  -3  10   1   4  -2  18]


In [31]:
idx = 3
j = 4 - idx
foo = ects[4][(2**j-1)::2**j]
print(len(foo))
np.sum(np.abs(foo - ects[idx]))

4800


0

In [34]:
Tvals = [4,8,16,32,64]
Tmax = max(Tvals)
Tmax

64

In [48]:
csrc = '../hpcc/clean/'
walnut_files = sorted(glob.glob(csrc + bname + '/*.tif'))
widx = 0
pa, fi = os.path.split(walnut_files[widx])
fname = os.path.splitext(fi)[0]
shell_file = src + bname + '/' + fname + '_shell.tif'
kernel_file = src + bname + '/' + fname + '_meat.tif'
print(fname)

for imgfile, imgname in zip([walnut_files[widx], shell_file, kernel_file], ['walnut', 'shell', 'kernel']):
    print(imgfile, imgname, sep='\t')

2014SBa_R1_T36_001
../hpcc/clean/2014SBa_R1_T36/2014SBa_R1_T36_001.tif	walnut
../hpcc/topology/2014SBa_R1_T36/2014SBa_R1_T36_001_shell.tif	shell
../hpcc/topology/2014SBa_R1_T36/2014SBa_R1_T36_001_meat.tif	kernel
